apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-script
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data-script
    spec:
      initContainers:
      - image: bshibilov/app312:datascript2
        name: my-init-container
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_DB_HOST
            value: "data"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        command: ['sh', '-c', "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo waiting for mydb; sleep 2; done"]
      containers:
        - image: bshibilov/app312:datascript2
          name: data-script
          env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_DB_HOST
            value: "data"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          resources: {}
      restartPolicy: Always
status: {}
