apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
        io.kompose.service: front
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: front
    spec:
      containers:
        - image: bshibilov/app312:app_front
          name: front
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
