apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    app: mysecret
type: Opaque
data:
  username: "cm9vdA=="
  password: "cm9vdA=="
  back-secret: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdEBkYXRhOjMzMDYvbXlkYXRhYmFzZQ==