version: "3"
services:
  web:    
    image: "bshibilov/app312:app_front"
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    image: "bshibilov/app312:app_back"
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    image: "bshibilov/app312:app_data"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
  
    image: "bshibilov/app312:script"
    networks:
      - myapp

networks:
  myapp:
